SESSION_NAME_KEY="SESSION_NAME"
SESSION_SEARCH_ID_KEY="SESSION_SEARCH_ID"
PORT_KEY="PORT"
STATUS_KEY = "STATUS"
SESSIONS_KEY = "SESSIONS"
 
# Leaderboard
PLAYERS_KEY = "PLAYERS"
PUID_KEY = "PUID"
NAME_KEY = "NAME"
KILLS_KEY = "KILLS"
DEATHS_KEY = "DEATHS"
WON_KEY = "WON"
WINS_KEY = "WINS"
LOSSES_KEY = "LOSSES"
ENTRIES_KEY = "ENTRIES"
 
SERVER_SECRET_HEADER = "X-Server-Secret"
ADMIN_SECRET_HEADER = "X-Admin-Secret"