;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ability.basicattack",DevComment="Ability Tag assigned to basic attack abilities")
+GameplayTagList=(Tag="ability.basicattack.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack1.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack1.pressed",DevComment="Tag used for events that will be signalled when basicattack1 input is pressed. Used for abilties which need additional combos when clicked")
+GameplayTagList=(Tag="ability.basicattack2.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack2.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack3.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack3.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack4.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack4.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack5.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack5.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack6.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack6.pressed",DevComment="")
+GameplayTagList=(Tag="ability.basicattack7.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.basicattack7.pressed",DevComment="")
+GameplayTagList=(Tag="ability.combo.change.combo01",DevComment="")
+GameplayTagList=(Tag="ability.combo.change.combo02",DevComment="")
+GameplayTagList=(Tag="ability.combo.change.combo03",DevComment="")
+GameplayTagList=(Tag="ability.combo.change.end",DevComment="")
+GameplayTagList=(Tag="ability.combo.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.combo.damage",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack",DevComment="Ability Tag assigned to heavy attack abilities")
+GameplayTagList=(Tag="ability.heavyattack1",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack2",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack3",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack.pressed",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack1.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack1.pressed",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack2.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack2.pressed",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack2.start",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack3.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack3.pressed",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack3.released",DevComment="")
+GameplayTagList=(Tag="ability.heavyattack3.shoot",DevComment="")
+GameplayTagList=(Tag="ability.passive.launch.activate",DevComment="")
+GameplayTagList=(Tag="ability.roll",DevComment="")
+GameplayTagList=(Tag="ability.stab.cooldown",DevComment="")
+GameplayTagList=(Tag="ability.stab.right",DevComment="")
+GameplayTagList=(Tag="attr.experience",DevComment="")
+GameplayTagList=(Tag="attr.soul",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.chris.slash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.projectile",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.projectile1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.reaction",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.skeleton",DevComment="")
+GameplayTagList=(Tag="GameplayCue.hit.slash",DevComment="")
+GameplayTagList=(Tag="role.hero",DevComment="")
+GameplayTagList=(Tag="stats.aim",DevComment="")
+GameplayTagList=(Tag="stats.attacking",DevComment="")
+GameplayTagList=(Tag="stats.crosshair",DevComment="")
+GameplayTagList=(Tag="stats.dead",DevComment="")
+GameplayTagList=(Tag="stats.fallback",DevComment="")
+GameplayTagList=(Tag="stats.health.empty",DevComment="")
+GameplayTagList=(Tag="stats.health.full",DevComment="")
+GameplayTagList=(Tag="stats.mana.empty",DevComment="")
+GameplayTagList=(Tag="stats.mana.full",DevComment="")
+GameplayTagList=(Tag="stats.rolling",DevComment="")
+GameplayTagList=(Tag="stats.stun",DevComment="")
+GameplayTagList=(Tag="stats.weapon.equipped",DevComment="")
+GameplayTagList=(Tag="stats.weapon.unequipped",DevComment="")

