// Christopher Naglik All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "NativeGameplayTags.h"
#include "ChrisGameplayTags.generated.h"



namespace ChrisGameplayTags
{
	// ── UI 2D ──────────────────────────────────
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Soft);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Main);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Shop);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Confirm);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Page_Change);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Page_Leave);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Tab_Change);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Open);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Close);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Flip);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Leaderboard_Open);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Leaderboard_Close);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Lobby_Continue);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Lobby_TeamSlot);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Skill);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Consumable);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Upgrade);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Reject);


	// ── Local player 2D ──────────────────────────────────
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Attack_Grunt);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Attack_Swoosh);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Hit_Light);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Hit_Heavy);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Combo_Hit);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Roll_Forward);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Roll_Backward);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Roll_Left);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Roll_Right);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_LowHealth);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_LevelUp);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Death);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Skill_Available);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_Player_Skill_Upgrade);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeavyAttack_Cooldown);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeavyAttack1_Cooldown);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeavyAttack2_Cooldown);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HeavyAttack3_Cooldown);
}


/**
 * 
 */
UCLASS()
class UChrisGameplayTags : public UObject
{
	GENERATED_BODY()
	
};
