// Christopher Naglik All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "NativeGameplayTags.h"
#include "ChrisGameplayTags.generated.h"



namespace ChrisGameplayTags
{
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Soft);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Main);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Navigate_Shop);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Confirm);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Page_Change);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Page_Leave);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Tab_Change);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Open);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Close);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Book_Flip);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Leaderboard_Open);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Leaderboard_Close);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Lobby_Continue);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Lobby_TeamSlot);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Skill);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Consumable);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Shop_Unlock_Upgrade);
	ANIMATIONTESTING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Audio_UI_Reject);
}


/**
 * 
 */
UCLASS()
class UChrisGameplayTags : public UObject
{
	GENERATED_BODY()
	
};
